//! RV32I opcode mnemonics.

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Opcode {
    Lui,
    Auipc,
    Jal,
    Jalr,
    Beq,
    Bne,
    Blt,
    Bge,
    Bltu,
    Bgeu,
    Lb,
    Lh,
    Lw,
    Lbu,
    Lhu,
    Sb,
    Sh,
    Sw,
    Addi,
    Slti,
    Sltiu,
    Xori,
    Ori,
    Andi,
    Slli,
    Srli,
    Srai,
    Add,
    Sub,
    Sll,
    Slt,
    Sltu,
    Xor,
    Srl,
    Sra,
    Or,
    And,
    Fence,
    Ecall,
    Ebreak,
}

impl sw_isa_core::Mnemonic for Opcode {
    fn mnemonic(&self) -> &'static str {
        match self {
            Opcode::Lui => "lui",
            Opcode::Auipc => "auipc",
            Opcode::Jal => "jal",
            Opcode::Jalr => "jalr",
            Opcode::Beq => "beq",
            Opcode::Bne => "bne",
            Opcode::Blt => "blt",
            Opcode::Bge => "bge",
            Opcode::Bltu => "bltu",
            Opcode::Bgeu => "bgeu",
            Opcode::Lb => "lb",
            Opcode::Lh => "lh",
            Opcode::Lw => "lw",
            Opcode::Lbu => "lbu",
            Opcode::Lhu => "lhu",
            Opcode::Sb => "sb",
            Opcode::Sh => "sh",
            Opcode::Sw => "sw",
            Opcode::Addi => "addi",
            Opcode::Slti => "slti",
            Opcode::Sltiu => "sltiu",
            Opcode::Xori => "xori",
            Opcode::Ori => "ori",
            Opcode::Andi => "andi",
            Opcode::Slli => "slli",
            Opcode::Srli => "srli",
            Opcode::Srai => "srai",
            Opcode::Add => "add",
            Opcode::Sub => "sub",
            Opcode::Sll => "sll",
            Opcode::Slt => "slt",
            Opcode::Sltu => "sltu",
            Opcode::Xor => "xor",
            Opcode::Srl => "srl",
            Opcode::Sra => "sra",
            Opcode::Or => "or",
            Opcode::And => "and",
            Opcode::Fence => "fence",
            Opcode::Ecall => "ecall",
            Opcode::Ebreak => "ebreak",
        }
    }
}
